//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools.CrashReporter.CrashReportWebSite.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Buggs_Users = new HashSet<Buggs_Users>();
            this.Buggs_Users1 = new HashSet<Buggs_Users>();
            this.Crashes = new HashSet<Crash>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public int UserGroupId { get; set; }
    
        public virtual ICollection<Buggs_Users> Buggs_Users { get; set; }
        public virtual ICollection<Buggs_Users> Buggs_Users1 { get; set; }
        public virtual ICollection<Crash> Crashes { get; set; }
        public virtual UserGroup UserGroup { get; set; }
    }
}
