// Copyright 1998-2013 Epic Games, Inc. All Rights Reserved.
#pragma once


#include "UTLocalMessage.generated.h"

UCLASS(Blueprintable, Abstract, NotPlaceable)
class UNREALTOURNAMENT_API UUTLocalMessage : public ULocalMessage
{
	GENERATED_UCLASS_BODY()

	/** Message area on HUD (index into UTHUD.MessageOffset[]) */
	UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category = Message)
	FName MessageArea;

	/** Can be used by a message zone to stylize an incoming localized message */
	UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category = Message)
	FName StyleTag;

	/** If true, this is a Game Status Announcement */
	UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category = Message)
	uint32 bIsStatusAnnouncement : 1;

	// If true, don't add to normal queue.  
	UPROPERTY(EditDefaultsOnly, Category = Message)
	uint32 bIsSpecial:1;

	// If true and special, only one can be in the HUD queue at a time.
	UPROPERTY(EditDefaultsOnly, Category = Message)
	uint32 bIsUnique:1;    

	// If true and special, only one can be in the HUD queue with the same switch value
	UPROPERTY(EditDefaultsOnly, Category = Message)
	uint32 bIsPartiallyUnique:1;    

	// If true, put a GetString on the console.
	UPROPERTY(EditDefaultsOnly, Category = Message)
	uint32 bIsConsoleMessage:1;    

	// if true, if sent to HUD multiple times, count up instances (only if bIsUnique)
	UPROPERTY(EditDefaultsOnly, Category = Message)
	uint32 bCountInstances:1;    

	// if true, allow overriding by anything else 
	UPROPERTY(EditDefaultsOnly, Category = Message)
	uint32 bOptionalSpoken : 1;

	// # of seconds to stay in HUD message queue.
	UPROPERTY(EditDefaultsOnly, Category = Message)
	float Lifetime;    

	// how long to delay playing this announcement
	UPROPERTY(EditDefaultsOnly, Category = Message)
	float AnnouncementDelay;

	virtual float GetAnnouncementDelay(int32 Switch);

	virtual bool ShouldPlayAnnouncement(const FClientReceiveData& ClientData) const;

	virtual void ClientReceive(const FClientReceiveData& ClientData) const override;

	UFUNCTION(BlueprintImplementableEvent)
	void OnClientReceive(APlayerController* LocalPC, int32 Switch, APlayerState* RelatedPlayerState_1, APlayerState* RelatedPlayerState_2, UObject* OptionalObject) const;

	UFUNCTION(BlueprintNativeEvent)
	FText ResolveMessage(int32 Switch = 0, bool bTargetsPlayerState1 = false, class APlayerState* RelatedPlayerState_1 = NULL, class APlayerState* RelatedPlayerState_2 = NULL, class UObject* OptionalObject = NULL) const;

	/** return the name of announcement to play for this message (if any); UTAnnouncer will map to an actual sound */
	UFUNCTION(BlueprintNativeEvent)
	FName GetAnnouncementName(int32 Switch, const UObject* OptionalObject) const;

	/** Return true if message should be displayed with large font. */
	virtual bool UseLargeFont(int32 MessageIndex) const;

	/** @TODO FIXMESTEVE - hack.  Instead just let message classes return font size index. */
	virtual bool UseMegaFont(int32 MessageIndex) const 
	{
		return false;
	};

	/** Return color of displayed message. */
	virtual FLinearColor GetMessageColor(int32 MessageIndex) const;

	/** How long to scale to 1 from initial message scale. */
	virtual float GetScaleInTime(int32 MessageIndex) const;

	/** Initial Message scale */
	virtual float GetScaleInSize(int32 MessageIndex) const;

	/** return whether this announcement should interrupt/cancel the passed in announcement */
	UFUNCTION(BlueprintNativeEvent)
	bool InterruptAnnouncement(int32 Switch, const UObject* OptionalObject, TSubclassOf<UUTLocalMessage> OtherMessageClass, int32 OtherSwitch, const UObject* OtherOptionalObject) const;

	/** return whether this announcement should be cancelled by the passed in announcement */
	UFUNCTION(BlueprintNativeEvent)
		bool CancelByAnnouncement(int32 Switch, const UObject* OptionalObject, TSubclassOf<UUTLocalMessage> OtherMessageClass, int32 OtherSwitch, const UObject* OtherOptionalObject) const;

	/** called when the UTAnnouncer plays the announcement sound - can be used to e.g. display HUD text at the same time */
	UFUNCTION(BlueprintNativeEvent)
	void OnAnnouncementPlayed(int32 Switch, const UObject* OptionalObject) const;

	/** called to precache announcer sounds at startup, since they're dynamically loaded to enable custom announcer packs */
	UFUNCTION(BlueprintNativeEvent)
	void PrecacheAnnouncements(class UUTAnnouncer* Announcer) const;

	virtual void GetArgs(FFormatNamedArguments& Args, int32 Switch = 0, bool bTargetsPlayerState1 = false, class APlayerState* RelatedPlayerState_1 = NULL, class APlayerState* RelatedPlayerState_2 = NULL, class UObject* OptionalObject = NULL) const;

	virtual FText GetText(int32 Switch = 0, bool bTargetsPlayerState1 = false, class APlayerState* RelatedPlayerState_1 = NULL, class APlayerState* RelatedPlayerState_2 = NULL, class UObject* OptionalObject = NULL) const;

	/**	Give Blueprints a way to override the text generated by this local message. */
	UFUNCTION(BlueprintNativeEvent)
	FText Blueprint_GetText(int32 Switch, bool bTargetsPlayerState1, class APlayerState* RelatedPlayerState_1, class APlayerState* RelatedPlayerState_2, class UObject* OptionalObject) const;

	virtual float GetLifeTime(int32 Switch) const;

	/** Range of 0 to 1, affects where announcement is inserted into pending announcements queue. */
	virtual float GetAnnouncementPriority(int32 Switch) const;

	/**	Give Blueprints a way to override the lifetime for this message */
	UFUNCTION(BlueprintNativeEvent)
	float Blueprint_GetLifeTime(int32 Switch) const;

	virtual bool IsConsoleMessage(int32 Switch) const;
	bool PartiallyDuplicates(int32 Switch1, int32 Switch2, class UObject* OptionalObject1, class UObject* OptionalObject2 );
};



