// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
#pragma once


// Objects
class UObjectBase;
class UObjectBaseUtility;
class	UObject;
class		UField;
class			UEnum;
class			UProperty;
class				UByteProperty;
class				UUInt16Property;
class				UUInt32Property;
class				UUInt64Property;
class				UInt8Property;
class				UInt16Property;
class				UIntProperty;
class				UInt64Property;
class				UBoolProperty;
class				UFloatProperty;
class				UDoubleProperty;
class				UObjectPropertyBase;
class				UObjectProperty;
class					UClassProperty;
class					UInterfaceProperty;
class					UWeakObjectProperty;
class					ULazyObjectProperty;
class					UAssetObjectProperty;
class				UNameProperty;
class				UStructProperty;
class				UStrProperty;
class				UTextProperty;
class				UArrayProperty;
class				UDelegateProperty;
class				UMulticastDelegateProperty;
class			UStruct;
class				UFunction;
class				UClass;
class				UScriptStruct;
class		FLinker;
class			FLinkerLoad;
class			FLinkerSave;
class		UPackage;
class		USystem;
class		UTextBuffer;
class		UPackageMap;
class		UObjectRedirector;