// Copyright 1998-2016 Epic Games, Inc. All Rights Reserved.

/*=============================================================================
	MetalCommon.usf: Common Metal shader code
=============================================================================*/

// Update this GUID to improve shader recompilation for Metal only shaders
// GUID = {06C79EC9-644E-4D22-ADA9-47DD4BB343D0f}
  
#pragma once
