// Copyright 1998-2016 Epic Games, Inc. All Rights Reserved.

/*=============================================================================
	MetalCommon.usf: Common Metal shader code
=============================================================================*/

// Update this GUID to improve shader recompilation for Metal only shaders
// GUID = {877F1616-B9F5-4148-9251-6E41D5DFF1D2}
  
#pragma once
