<?xml version="1.0" encoding="utf-8"?><Database Name="CrashReport" Class="CrashReportDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=db-09;Initial Catalog=CrashReport;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CrashReportConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Buggs" Member="Buggs">
    <Type Name="Bugg">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TTPID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pattern" Type="System.String" DbType="VarChar(800) NOT NULL" CanBeNull="false" />
      <Column Name="NumberOfCrashes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumberOfUsers" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeOfFirstCrash" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TimeOfLastCrash" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="FixedChangeList" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BuildVersion" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="CrashType" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="Bugg_Buggs_Crash" Member="Buggs_Crashes" ThisKey="Id" OtherKey="BuggId" Type="Buggs_Crash" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="UserGroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Buggs_User" Member="Buggs_Users" ThisKey="Id" OtherKey="UserNameId" Type="Buggs_User" />
      <Association Name="User_Crash" Member="CrashesFromUserId" Storage="_Crashes" ThisKey="Id" OtherKey="UserNameId" Type="Crash" />
      <Association Name="UserGroup_User" Member="UserGroup" ThisKey="UserGroupId" OtherKey="Id" Type="UserGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Buggs_Crashes" Member="Buggs_Crashes">
    <Type Name="Buggs_Crash">
      <Column Name="BuggId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CrashId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Crash_Buggs_Crash" Member="Crash" ThisKey="CrashId" OtherKey="Id" Type="Crash" IsForeignKey="true" />
      <Association Name="Bugg_Buggs_Crash" Member="Bugg" ThisKey="BuggId" OtherKey="Id" Type="Bugg" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Buggs_UserGroups" Member="Buggs_UserGroups">
    <Type Name="Buggs_UserGroup">
      <Column Name="BuggId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserGroupId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="UserGroup_Buggs_UserGroup" Member="UserGroup" ThisKey="UserGroupId" OtherKey="Id" Type="UserGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Buggs_Users" Member="Buggs_Users">
    <Type Name="Buggs_User">
      <Column Name="BuggId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(64) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserNameId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_Buggs_User" Member="User" ThisKey="UserNameId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Crashes" Member="Crashes">
    <Type Name="Crash">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="GameName" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="TimeOfCrash" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ChangeListVersion" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="PlatformName" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="EngineMode" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="RawCallStack" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Pattern" Type="System.String" DbType="VarChar(800)" CanBeNull="true" />
      <Column Name="CommandLine" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="ComputerName" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="FixedChangeList" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="LanguageExt" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="Module" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="BuildVersion" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="BaseDir" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="TTPID" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="Processed" Member="bAllowToBeContacted" Storage="_Processed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HasLogFile" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HasMiniDumpFile" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HasVideoFile" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HasDiagnosticsFile" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Branch" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="UserNameId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CrashType" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="HasMetaData" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SourceContext" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="EpicAccountId" Type="System.String" DbType="varchar(64)" CanBeNull="true" />
      <Column Name="EngineVersion" Type="System.String" DbType="varchar(64)" CanBeNull="true" />
      <Association Name="Crash_Buggs_Crash" Member="Buggs_Crashes" ThisKey="Id" OtherKey="CrashId" Type="Buggs_Crash" />
      <Association Name="User_Crash" Member="UserById" Storage="_User" ThisKey="UserNameId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FunctionCalls" Member="FunctionCalls">
    <Type Name="FunctionCall">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Call" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserGroups" Member="UserGroups">
    <Type Name="UserGroup">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Association Name="UserGroup_User" Member="Users" ThisKey="Id" OtherKey="UserGroupId" Type="User" />
      <Association Name="UserGroup_Buggs_UserGroup" Member="Buggs_UserGroups" ThisKey="Id" OtherKey="UserGroupId" Type="Buggs_UserGroup" />
    </Type>
  </Table>
  <Table Name="dbo.UsersMapping" Member="UsersMappings">
    <Type Name="UsersMapping">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserEmail" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="MachineId" Type="System.String" DbType="NChar(32)" CanBeNull="true" />
      <Column Name="EpicAccountId" Type="System.String" DbType="NChar(32)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
    </Type>
  </Table>
</Database>