// Copyright 1998-2016 Epic Games, Inc. All Rights Reserved.

#pragma once

#include "Developer/AssetTools/Public/AssetToolsModule.h"
#include "Developer/DesktopPlatform/Public/PlatformInfo.h"
#include "Developer/DesktopWidgets/Public/Widgets/Input/SFilePathPicker.h"

#include "Editor/ContentBrowser/Public/ContentBrowserModule.h"
#include "Editor/EditorStyle/Public/EditorStyle.h"
#include "Editor/PropertyEditor/Public/DetailCategoryBuilder.h"
#include "Editor/PropertyEditor/Public/DetailLayoutBuilder.h"
#include "Editor/PropertyEditor/Public/DetailWidgetRow.h"
#include "Editor/PropertyEditor/Public/IDetailPropertyRow.h"
#include "Editor/PropertyEditor/Public/IDetailsView.h"
#include "Editor/PropertyEditor/Public/PropertyEditorModule.h"
#include "Editor/PropertyEditor/Public/PropertyHandle.h"
#include "Editor/TextureEditor/Public/TextureEditor.h"
#include "Editor/UnrealEd/Public/Factories.h"
#include "Editor/UnrealEd/Public/ScopedTransaction.h"
#include "Editor/UnrealEd/Public/UnrealEd.h"
#include "Editor/UnrealEd/Public/Toolkits/AssetEditorManager.h"
#include "Editor/UnrealEd/Public/Toolkits/AssetEditorToolkit.h"
#include "Editor/UnrealEd/Public/Toolkits/IToolkit.h"
#include "Editor/WorkspaceMenuStructure/Public/WorkspaceMenuStructureModule.h"

#include "Runtime/Core/Public/Core.h"
#include "Runtime/Core/Public/Modules/ModuleInterface.h"
#include "Runtime/Core/Public/Modules/ModuleManager.h"
#include "Runtime/CoreUObject/Public/CoreUObject.h"
#include "Runtime/Engine/Classes/Components/AudioComponent.h"
#include "Runtime/Engine/Classes/Materials/Material.h"
#include "Runtime/Engine/Classes/Materials/MaterialExpressionTextureSample.h"
#include "Runtime/Engine/Public/AudioDevice.h"
#include "Runtime/Engine/Public/Engine.h"
#include "Runtime/Engine/Public/Slate/SceneViewport.h"
#include "Runtime/Engine/Public/Slate/SlateTextures.h"
#include "Runtime/Media/Public/IMediaControls.h"
#include "Runtime/Media/Public/IMediaModule.h"
#include "Runtime/Media/Public/IMediaOutput.h"
#include "Runtime/Media/Public/IMediaPlayer.h"
#include "Runtime/Media/Public/IMediaPlayerFactory.h"
#include "Runtime/Media/Public/IMediaTracks.h"
#include "Runtime/MediaAssets/Public/FileMediaSource.h"
#include "Runtime/MediaAssets/Public/MediaPlayer.h"
#include "Runtime/MediaAssets/Public/MediaPlaylist.h"
#include "Runtime/MediaAssets/Public/MediaSoundWave.h"
#include "Runtime/MediaAssets/Public/MediaSource.h"
#include "Runtime/MediaAssets/Public/MediaTexture.h"
#include "Runtime/MediaAssets/Public/PlatformMediaSource.h"
#include "Runtime/MediaAssets/Public/StreamMediaSource.h"
#include "Runtime/RenderCore/Public/TickableObjectRenderThread.h"
#include "Runtime/Slate/Public/SlateBasics.h"
#include "Runtime/Slate/Public/Framework/Notifications/NotificationManager.h"
#include "Runtime/Slate/Public/Widgets/Docking/SDockTab.h"
#include "Runtime/Slate/Public/Widgets/Input/SNumericEntryBox.h"
#include "Runtime/Slate/Public/Widgets/Layout/SScaleBox.h"
#include "Runtime/Slate/Public/Widgets/Notifications/SNotificationList.h"
#include "Runtime/SlateCore/Public/Styling/SlateStyle.h"


/** Log category for the MediaPlayerEditor module. */
DECLARE_LOG_CATEGORY_EXTERN(LogMediaPlayerEditor, Log, All);
