// Copyright 1998-2016 Epic Games, Inc. All Rights Reserved.

#pragma once

#include "Editor/KismetCompiler/Public/BlueprintCompilerCppBackendInterface.h"

struct FNativizationSummary
{
	TMap<FStringAssetReference, int32> InaccessiblePropertyStat;
};

/**
 * The public interface to this module
 */
class IBlueprintCompilerCppBackendModule : public IBlueprintCompilerCppBackendModuleInterface
{
public:
	/**
	 * Aimed to help coordinate #include statements (generated by the backend) 
	 * and target file paths. A centralized function, that'll generate a 
	 * source-file name for the supplied asset object.
	 * 
	 * @param  AssetObj    The asset you want a source-file name for.
	 * @return The filename (without an extension) for the target asset.
	 */
	virtual FString ConstructBaseFilename(const UObject* AssetObj) = 0;


	DECLARE_DELEGATE_RetVal(FString, FPCHFilenameQuery);
	/**
	 * Provides a hook so that external modules can specify the PCH file that 
	 * should be used for generated source.
	 * 
	 * @return A delegate that will be used to fill out the shared include statement in generated source.
	 */
	virtual FPCHFilenameQuery& OnPCHFilenameQuery() = 0;


	DECLARE_DELEGATE_RetVal_OneParam(bool, FIsTargetedForConversionQuery, const UObject*);
	/**
	 * Provides a hook so that external modules can specify which assets will 
	 * and won't be converted (so the backend knows how to handle cross asset 
	 * references).
	 * 
	 * @return A delegate that will used to determine how to generate cross asset references (in generated source).
	 */
	virtual FIsTargetedForConversionQuery& OnIsTargetedForConversionQuery() = 0;

	/**
	 *	Cpp is generated from a duplicate of the original Blueprint. This map stores info about the original BPGC.
	 */
	virtual TMap<TWeakObjectPtr<UClass>, TWeakObjectPtr<UClass> >& GetOriginalClassMap() = 0;

	/**
	 *	Provides a hook so that external modules can mark some unconverted blueprints as necessary for the generated native code.
	 */
	DECLARE_DELEGATE_OneParam(FMarkUnconvertedBlueprintAsNecessary, TAssetPtr<UBlueprint>);
	virtual FMarkUnconvertedBlueprintAsNecessary& OnIncludingUnconvertedBP() = 0;

	DECLARE_DELEGATE_RetVal_OneParam(bool, FIsFunctionUsedInADelegate, const UFunction*);
	virtual FIsFunctionUsedInADelegate& GetIsFunctionUsedInADelegateCallback() = 0;

	// Collect functions that are used by delegates - they must have UFUNCTION macro
	BLUEPRINTCOMPILERCPPBACKEND_API static TArray<class UFunction*> CollectBoundFunctions(class UBlueprint* BP);

	virtual TSharedPtr<FNativizationSummary>& NativizationSummary() = 0;
};

