// Copyright 1998-2016 Epic Games, Inc. All Rights Reserved.

#include "Editor.h"
#include "LevelEditor.h"
#include "PersonaModule.h"
#include "Animation/AnimationRecordingSettings.h"
#include "AnimationRecorder.h"
#include "SlateBasics.h"
#include "WorkspaceMenuStructureModule.h"
#include "PropertyEditing.h"
#include "MovieScene.h"
#include "KeyParams.h"
#include "IKeyframeSection.h"
#include "MovieSceneSection.h"
#include "LevelSequence.h"
#include "IMovieSceneSectionRecorder.h"
#include "IMovieSceneSectionRecorderFactory.h"